# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170413_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.CharField(blank=True, choices=[('home', 'home'), ('visitor', 'visitor'), ('double default', 'double default')], max_length=31, null=True),
        ),
    ]
