# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170414_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(blank=True, choices=[('completed', 'completed'), ('retired', 'retired'), ('default', 'default'), ('timed match', 'timed match')], max_length=63, null=True),
        ),
    ]
